### ISSUE TITLE
Use new ROF criteria for stream order and length

### ISSUE THREAD

**Issue by MichaelSmith-NOAA** [kvanwerkhoven/rti-nwc#11]
April 1, 2021.  WPOD requested that ISED use the new ROF to be operational April 21. This new version will:
1) only consider the ROF criteria in streams of order 4 and below;
2) use the reach length instead of number of reaches to compute the % reaches in ROF for a HUC.  The % is computed as the total reach length meeting ROF criteria divided by the total reach length of streams 4th order and below.

**Comment by kvanwerkhoven** [comment]
@MichaelSmith-NOAA  This is done
