### ISSUE TITLE
WPOD request: Use WPC color scheme for precipitation 

### ISSUE THREAD

**Issue by MichaelSmith-NOAA** [kvanwerkhoven/rti-nwc#8]
May 19, 2021.  WPOD requests to use the precipitation color bar scheme that WPC uses.  See   This would enhance consistency for WPOD analysis of various info sources.  The WPC web site is here:  https://www.wpc.ncep.noaa.gov/qpf/qpf2.shtml

**Comment by aaraney** [comment]
I am not sure these are equivalent, but [this](https://matplotlib.org/stable/gallery/color/colormap_reference.html) may be a good place to start. Specifically `gist_ncar` see the bottom of the page.

Likewise, there are also a few color maps that may be relevant in the [`metpy` project](https://unidata.github.io/MetPy/latest/api/generated/metpy.plots.ctables.html).

**Comment by aaraney** [comment]
Katie mentioned in meeting on Friday 21, this has been resolved. With that I am going to close thsi. @kvanwerkhoven if you have further comments, please add them below!
